[package]
name = "strql"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.16.0"
thiserror = "2.0.17"
serde_json = "1.0"
miette = { version = "7.6.0", features = ["fancy"] }

[dev-dependencies]
pretty_assertions = "1.4"
